CREATE TABLE IF NOT EXISTS `merchant_stay_orders` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `merchant_user_id` int unsigned NOT NULL COMMENT '商家用户ID',
  `order_no` varchar(40) NOT NULL COMMENT '入住单号',
  `source_type` enum('walk_in','reservation') NOT NULL DEFAULT 'walk_in' COMMENT '来源类型：散客/预订',
  `status` enum('reserved','checked_in','checked_out','cancelled') NOT NULL DEFAULT 'reserved' COMMENT '入住状态',
  `room_id` int unsigned NOT NULL COMMENT '房间ID',
  `room_number_snapshot` varchar(20) NOT NULL DEFAULT '' COMMENT '房间号快照',
  `room_type_id_snapshot` int unsigned NOT NULL DEFAULT '0' COMMENT '房型ID快照',
  `room_type_name_snapshot` varchar(60) NOT NULL DEFAULT '' COMMENT '房型名称快照',
  `guest_count` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '入住人数',
  `primary_guest_name` varchar(30) NOT NULL DEFAULT '' COMMENT '主入住人姓名',
  `primary_guest_id_no` varchar(40) NOT NULL DEFAULT '' COMMENT '主入住人证件号',
  `primary_guest_phone` varchar(20) NOT NULL DEFAULT '' COMMENT '主入住人手机号',
  `primary_guest_gender` enum('male','female','unknown') NOT NULL DEFAULT 'unknown' COMMENT '主入住人性别',
  `planned_check_in_date` date NOT NULL COMMENT '计划入住日期',
  `planned_check_out_date` date NOT NULL COMMENT '计划离店日期',
  `actual_check_in_at` datetime DEFAULT NULL COMMENT '实际入住时间',
  `actual_check_out_at` datetime DEFAULT NULL COMMENT '实际离店时间',
  `nightly_price_cents` int unsigned NOT NULL DEFAULT '0' COMMENT '单晚房费（分）',
  `stay_nights` int unsigned NOT NULL DEFAULT '1' COMMENT '入住晚数',
  `room_charge_cents` int unsigned NOT NULL DEFAULT '0' COMMENT '房费总额（分）',
  `deposit_cents` int unsigned NOT NULL DEFAULT '0' COMMENT '押金（分）',
  `settlement_paid_cents` int unsigned NOT NULL DEFAULT '0' COMMENT '结算实收（分）',
  `balance_cents` int NOT NULL DEFAULT '0' COMMENT '应收应退差额（分，正=应收，负=应退）',
  `payment_method` enum('cash','wechat','alipay','bank_card','other') NOT NULL DEFAULT 'cash' COMMENT '支付方式',
  `remark` varchar(500) NOT NULL DEFAULT '' COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_merchant_stay_orders_order_no` (`order_no`),
  KEY `idx_merchant_stay_orders_merchant_status` (`merchant_user_id`,`status`),
  KEY `idx_merchant_stay_orders_room` (`merchant_user_id`,`room_id`),
  KEY `idx_merchant_stay_orders_checkin` (`merchant_user_id`,`planned_check_in_date`,`planned_check_out_date`),
  CONSTRAINT `fk_merchant_stay_orders_user` FOREIGN KEY (`merchant_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_merchant_stay_orders_room` FOREIGN KEY (`room_id`) REFERENCES `merchant_rooms` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商家入住订单表';

CREATE TABLE IF NOT EXISTS `merchant_stay_guests` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `stay_order_id` int unsigned NOT NULL COMMENT '入住订单ID',
  `merchant_user_id` int unsigned NOT NULL COMMENT '商家用户ID',
  `is_primary` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否主入住人',
  `name` varchar(30) NOT NULL DEFAULT '' COMMENT '住客姓名',
  `id_no` varchar(40) NOT NULL DEFAULT '' COMMENT '证件号',
  `phone` varchar(20) NOT NULL DEFAULT '' COMMENT '手机号',
  `gender` enum('male','female','unknown') NOT NULL DEFAULT 'unknown' COMMENT '性别',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_merchant_stay_guests_order` (`stay_order_id`,`is_primary`),
  KEY `idx_merchant_stay_guests_merchant` (`merchant_user_id`),
  KEY `idx_merchant_stay_guests_id_no` (`merchant_user_id`,`id_no`),
  CONSTRAINT `fk_merchant_stay_guests_order` FOREIGN KEY (`stay_order_id`) REFERENCES `merchant_stay_orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_merchant_stay_guests_user` FOREIGN KEY (`merchant_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商家入住住客表';

CREATE TABLE IF NOT EXISTS `merchant_stay_extensions` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `stay_order_id` int unsigned NOT NULL COMMENT '入住订单ID',
  `merchant_user_id` int unsigned NOT NULL COMMENT '商家用户ID',
  `old_checkout_date` date NOT NULL COMMENT '续住前离店日期',
  `new_checkout_date` date NOT NULL COMMENT '续住后离店日期',
  `added_nights` int unsigned NOT NULL DEFAULT '0' COMMENT '新增晚数',
  `added_amount_cents` int unsigned NOT NULL DEFAULT '0' COMMENT '新增金额（分）',
  `remark` varchar(500) NOT NULL DEFAULT '' COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_merchant_stay_extensions_order` (`stay_order_id`,`created_at`),
  KEY `idx_merchant_stay_extensions_merchant` (`merchant_user_id`),
  CONSTRAINT `fk_merchant_stay_extensions_order` FOREIGN KEY (`stay_order_id`) REFERENCES `merchant_stay_orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_merchant_stay_extensions_user` FOREIGN KEY (`merchant_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商家入住续住记录表';
